version: '3.0'
services:
  redis:
    container_name: redisx
    image: redis
    ports:
      - 6380:6379
  postgres:
    container_name: postgresx
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: Pass@123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5435:5432
  nest:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres
    command: 'npm run start'
