{
  'databases':
    {
      'postgres':
        {
          'url': 'postgres://postgres:Pass%40123@localhost:5435/postgres',
          'logging': false,
          'sync': false,
          'entity': { 'autoload': true, 'path': '' },
          'dropSchema': false,
          'migration': { 'run': false },
        },
    },
  'secret':
    {
      'jwt':
        {
          'accessSecret': 'Secret123',
          'refreshSecret': 'Secret123',
          'accessExpiresIn': '60s',
          'refreshExpiresIn': '30d',
        },
      'password': { 'saltRound': 10 },
    },
}
